"""Add loction column to auditions

Revision ID: 9fc4d9f3fcfe
Revises: f274f935136f
Create Date: 2023-06-29 15:59:02.368183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc4d9f3fcfe'
down_revision = 'f274f935136f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auditions', sa.Column('location', sa.String(), nullable=True))
    op.create_foreign_key(op.f('fk_auditions_role_id_roles'), 'auditions', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_auditions_role_id_roles'), 'auditions', type_='foreignkey')
    op.drop_column('auditions', 'location')
    # ### end Alembic commands ###
